---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    driver:
      customize:
        memory: 1024
        cpus: 1
      network:
        - ["forwarded_port", {guest: 7080, host: 1280}]
  - name: ubuntu-14.04
    driver:
      customize:
        memory: 1024
        cpus: 1
      network:
        - ["forwarded_port", {guest: 7080, host: 1480}]

suites:
  - name: default
    run_list:
      - recipe[unifi-video]
    attributes: {}
