---
driver_config:
  digitalocean_api_key: <%= ENV['DIGITALOCEAN_ACCESS_TOKEN'] %>
  private_networking: false

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
- name: ubuntu-12-04-x64
  driver_plugin: digitalocean
  driver_config:
    image: ubuntu-12-04-x64
    size: 512mb
    region: ams3
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>
- name: ubuntu-14-04-x64
  driver_plugin: digitalocean
  driver_config:
    image: ubuntu-14-04-x64
    size: 512mb
    region: ams3
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>
- name: debian-7-0-x64
  driver_plugin: digitalocean
  driver_config:
    image: debian-7-0-x64
    size: 512mb
    region: ams3
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>
- name: debian-8-1-x64
  driver_plugin: digitalocean
  driver_config:
    image: debian-8-1-x64
    size: 512mb
    region: ams3
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>

suites:
- name: default
  run_list:
    - recipe[unifi-video]
  attributes: {}
