---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    driver:
      customize:
        memory: 512
        cpus: 1
      network:
        - ["private_network", {'ip': '192.168.56.10'}]
  - name: ubuntu-14.04
    driver:
      customize:
        memory: 512
        cpus: 1
      network:
        - ["private_network", {'ip': '192.168.56.10'}]
  - name: debian-7.8
    driver:
      customize:
        memory: 512
        cpus: 1
      network:
        - ["private_network", {'ip': '192.168.56.10'}]
  - name: debian-8.1
    driver:
      customize:
        memory: 512
        cpus: 1
      network:
        - ["private_network", {'ip': '192.168.56.10'}]

suites:
  - name: default
    run_list:
      - recipe[unifi-video]
    attributes: {}
